### ISSUE TITLE
flake8 versions >=5 throw pre-commit errors

### ISSUE THREAD

**Issue by Georacer** [AvyFly/parasect#213]
Full error printout:

```

flake8...................................................................Failed
- hook id: flake8
- exit code: 1

Traceback (most recent call last):
  File "<install_dir>/parasect/.nox/pre-commit/lib/python3.11/site-packages/flake8/plugins/finder.py", line 291, in _load_plugin
    obj = plugin.entry_point.load()
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/george/.pyenv/versions/3.11.3/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/george/.pyenv/versions/3.11.3/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<install_dir>/parasect/.nox/pre-commit/lib/python3.11/site-packages/flake8_bandit.py", line 10, in <module>
    from flake8.options.config import ConfigFileFinder
ImportError: cannot import name 'ConfigFileFinder' from 'flake8.options.config' (<install_dir>/parasect/.nox/pre-commit/lib/python3.11/site-packages/flake8/options/config.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<install_dir>/parasect/.nox/pre-commit/bin/flake8", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "<install_dir>/parasect/.nox/pre-commit/lib/python3.11/site-packages/flake8/main/cli.py", line 23, in main
    app.run(argv)
  File "<install_dir>/parasect/.nox/pre-commit/lib/python3.11/site-packages/flake8/main/application.py", line 198, in run
    self._run(argv)
  File "<install_dir>/parasect/.nox/pre-commit/lib/python3.11/site-packages/flake8/main/application.py", line 186, in _run
    self.initialize(argv)
  File "<install_dir>/parasect/.nox/pre-commit/lib/python3.11/site-packages/flake8/main/application.py", line 165, in initialize
    self.plugins, self.options = parse_args(argv)
                                 ^^^^^^^^^^^^^^^^
  File "<install_dir>/parasect/.nox/pre-commit/lib/python3.11/site-packages/flake8/options/parse_args.py", line 42, in parse_args
    plugins = finder.load_plugins(raw_plugins, plugin_opts)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<install_dir>/parasect/.nox/pre-commit/lib/python3.11/site-packages/flake8/plugins/finder.py", line 365, in load_plugins
    return _classify_plugins(_import_plugins(plugins, opts), opts)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<install_dir>/parasect/.nox/pre-commit/lib/python3.11/site-packages/flake8/plugins/finder.py", line 307, in _import_plugins
    return [_load_plugin(p) for p in plugins]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<install_dir>/parasect/.nox/pre-commit/lib/python3.11/site-packages/flake8/plugins/finder.py", line 307, in <listcomp>
    return [_load_plugin(p) for p in plugins]
            ^^^^^^^^^^^^^^^
  File "<install_dir>/parasect/.nox/pre-commit/lib/python3.11/site-packages/flake8/plugins/finder.py", line 293, in _load_plugin
    raise FailedToLoadPlugin(plugin.package, e)
flake8.exceptions.FailedToLoadPlugin: Flake8 failed to load plugin "flake8-bandit" due to cannot import name 'ConfigFileFinder' from 'flake8.options.config' (<install_dir>/parasect/.nox/pre-commit/lib/python3.11/site-packages/flake8/options/config.py).
```

**Comment by Georacer** [comment]
This has been fixed by updating flake8-bandit.
